#!/bin/sh
module="scull"
device="scull"
mode="664"

# 给定适当的组属性及许可，并修改属性组
group="staff"
grep -q '^staff:' /etc/group || group="wheel"

# 使用传入到该脚本的所有参数调用insmod，同时使用路径名来指定模块位置
/sbin/insmod ./$module.ko $* || exit 1

# 删除原有节点
rm -f /dev/${device}[0-3]

major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

rm -f /dev/${device}[0-3]
mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1
mknod /dev/${device}2 c $major 2
mknod /dev/${device}3 c $major 3
ln -sf ${device}0 /dev/${device}

chgrp $group /dev/${device}[0-3]
chgrp $mode /dev/${device}[0-3]